; ==========================================================
; Carbie-Syncer PlatformIO Configuration
; ==========================================================

; This tells PlatformIO which environment to build by default.
; "Generic" version should work for anyone 
[platformio]
default_envs = esp32-s3-generic

; ----------------------------------------------------------
; 1. THE SAFE DEFAULT (Works on ESP32-S3 Mini, Zero, & Standard)
; ----------------------------------------------------------
[env:esp32-s3-generic]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200